from flask import Flask
from flask import render_template
from localsettings import DEBUG

app = Flask(__name__)


# routes
# -----------------------------------------------------------------------------

@app.route('/')
def index_route(params={}):
    images = [{
        'id': '6',
        'orientation': 'landscape',
    }, {
        'id': '10',
        'orientation': 'portrait',
    }, {
        'id': '12',
        'orientation': 'portrait',
    }, {
        'id': '18',
        'orientation': 'portrait',
    }, {
        'id': '21',
        'orientation': 'portrait',
    }, {
        'id': '23',
        'orientation': 'portrait',
    }, {
        'id': '27',
        'orientation': 'landscape',
    }, {
        'id': '31',
        'orientation': 'portrait',
    }, {
        'id': '37',
        'orientation': 'portrait',
    }, {
        'id': '39',
        'orientation': 'landscape',
    }, {
        'id': '41',
        'orientation': 'landscape',
    }, {
        'id': '44',
        'orientation': 'portrait',
    }, {
        'id': '48',
        'orientation': 'portrait',
    }, {
        'id': '51',
        'orientation': 'landscape',
    }, {
        'id': '53',
        'orientation': 'portrait',
    }, {
        'id': '56',
        'orientation': 'portrait',
    }, {
        'id': '59',
        'orientation': 'landscape',
    }, {
        'id': '62',
        'orientation': 'portrait',
    }, {
        'id': '63',
        'orientation': 'landscape',
    }, {
        'id': '65',
        'orientation': 'portrait',
    }, {
        'id': '67',
        'orientation': 'landscape',
    }, {
        'id': '70',
        'orientation': 'portrait',
    }, {
        'id': '73',
        'orientation': 'portrait',
    }, {
        'id': '81',
        'orientation': 'landscape',
    }, {
        'id': '83',
        'orientation': 'portrait',
    }, {
        'id': '86',
        'orientation': 'portrait',
    }, {
        'id': '87',
        'orientation': 'landscape',
    }, {
        'id': '90',
        'orientation': 'landscape',
    }, {
        'id': '97',
        'orientation': 'portrait',
    }, {
        'id': '102',
        'orientation': 'portrait',
    }, {
        'id': '111',
        'orientation': 'portrait',
    }, {
        'id': '110',
        'orientation': 'portrait',
    }, {
        'id': '122',
        'orientation': 'portrait',
    }, {
        'id': '124',
        'orientation': 'portrait',
    }, {
        'id': '129',
        'orientation': 'portrait',
    }, {
        'id': '135',
        'orientation': 'portrait',
    }, {
        'id': '138',
        'orientation': 'portrait',
    }, {
        'id': '149',
        'orientation': 'portrait',
    }, {
        'id': '153',
        'orientation': 'portrait',
    }, {
        'id': '158',
        'orientation': 'portrait',
    }, {
        'id': '167',
        'orientation': 'landscape',
    }, {
        'id': '173',
        'orientation': 'portrait',
    }, {
        'id': '175',
        'orientation': 'portrait',
    }, {
        'id': '176',
        'orientation': 'portrait',
    }, {
        'id': '177',
        'orientation': 'portrait',
    }, {
        'id': '180',
        'orientation': 'portrait',
    }, {
        'id': '181',
        'orientation': 'portrait',
    }, {
        'id': '184',
        'orientation': 'landscape',
    }, {
        'id': '191',
        'orientation': 'portrait',
    }, {
        'id': '196',
        'orientation': 'landscape',
    }, {
        'id': '220',
        'orientation': 'portrait',
    }, {
        'id': '234',
        'orientation': 'portrait',
    }, {
        'id': '238',
        'orientation': 'portrait',
    }, {
        'id': '251',
        'orientation': 'landscape',
    }, {
        'id': '262',
        'orientation': 'portrait',
    }, {
        'id': '270',
        'orientation': 'portrait',
    }, {
        'id': '276',
        'orientation': 'landscape',
    }, {
        'id': '280',
        'orientation': 'landscape',
    }, {
        'id': '288',
        'orientation': 'portrait',
    }, {
        'id': '289',
        'orientation': 'landscape',
    }, {
        'id': '295',
        'orientation': 'landscape',
    }, {
        'id': '311',
        'orientation': 'landscape',
    }, {
        'id': '320',
        'orientation': 'landscape',
    }, {
        'id': '323',
        'orientation': 'portrait',
    }, {
        'id': '328',
        'orientation': 'landscape',
    }, {
        'id': '334',
        'orientation': 'landscape',
    }, {
        'id': '339',
        'orientation': 'landscape',
    }, {
        'id': '340',
        'orientation': 'portrait',
    }, {
        'id': '345',
        'orientation': 'landscape',
    }, {
        'id': '351',
        'orientation': 'portrait',
    }, {
        'id': '356',
        'orientation': 'portrait',
    }, {
        'id': '361',
        'orientation': 'portrait',
    }, {
        'id': '366',
        'orientation': 'landscape',
    }, {
        'id': '370',
        'orientation': 'portrait',
    }, {
        'id': '374',
        'orientation': 'landscape',
    }, {
        'id': '388',
        'orientation': 'landscape',
    }, {
        'id': '393',
        'orientation': 'landscape',
    }, {
        'id': '397',
        'orientation': 'portrait',
    }, {
        'id': '401',
        'orientation': 'landscape',
    }, {
        'id': '407',
        'orientation': 'landscape',
    }, {
        'id': '412',
        'orientation': 'portrait',
    }, {
        'id': '418',
        'orientation': 'landscape',
    }, {
        'id': '423',
        'orientation': 'portrait',
    }, {
        'id': '424',
        'orientation': 'portrait',
    }, {
        'id': '425',
        'orientation': 'portrait',
    }, {
        'id': '432',
        'orientation': 'portrait',
    }, {
        'id': '436',
        'orientation': 'portrait',
    }, {
        'id': '442',
        'orientation': 'landscape',
    }, {
        'id': '447',
        'orientation': 'portrait',
    }, {
        'id': '451',
        'orientation': 'portrait',
    }, {
        'id': '452',
        'orientation': 'portrait',
    }, {
        'id': '459',
        'orientation': 'portrait',
    }, {
        'id': '463',
        'orientation': 'landscape',
    }, {
        'id': '469',
        'orientation': 'landscape',
    }, {
        'id': '475',
        'orientation': 'portrait',
    }, {
        'id': '483',
        'orientation': 'landscape',
    }, {
        'id': '490',
        'orientation': 'portrait',
    }, {
        'id': '491',
        'orientation': 'landscape',
    }, {
        'id': '506',
        'orientation': 'landscape',
    }, {
        'id': '514',
        'orientation': 'portrait',
    }, {
        'id': '520',
        'orientation': 'portrait',
    }, {
        'id': '524',
        'orientation': 'portrait',
    }, {
        'id': '540',
        'orientation': 'portrait',
    }, {
        'id': '555',
        'orientation': 'portrait',
    }, {
        'id': '560',
        'orientation': 'landscape',
    }, {
        'id': '567',
        'orientation': 'landscape',
    }, {
        'id': '576',
        'orientation': 'landscape',
    }, {
        'id': '577',
        'orientation': 'landscape',
    }, {
        'id': '579',
        'orientation': 'landscape',
    }, {
        'id': '580',
        'orientation': 'landscape',
    }, {
        'id': '586',
        'orientation': 'landscape',
    }, {
        'id': '589',
        'orientation': 'portrait',
    }, {
        'id': '605',
        'orientation': 'portrait',
    }, {
        'id': '612',
        'orientation': 'landscape',
    }, {
        'id': '622',
        'orientation': 'landscape',
    }, {
        'id': '630',
        'orientation': 'portrait',
    }, {
        'id': '641',
        'orientation': 'landscape',
    }, {
        'id': '659',
        'orientation': 'portrait',
    }, {
        'id': '665',
        'orientation': 'landscape',
    }, {
        'id': '682',
        'orientation': 'portrait',
    }, {
        'id': '702',
        'orientation': 'landscape',
    }, {
        'id': '706',
        'orientation': 'portrait',
    }, {
        'id': '732',
        'orientation': 'portrait',
    }, {
        'id': '744',
        'orientation': 'portrait',
    }, {
        'id': '748',
        'orientation': 'portrait',
    }, {
        'id': '754',
        'orientation': 'landscape',
    }, {
        'id': '765',
        'orientation': 'portrait',
    }, {
        'id': '785',
        'orientation': 'portrait',
    }, {
        'id': '787',
        'orientation': 'portrait',
    }, {
        'id': '789',
        'orientation': 'landscape',
    }, {
        'id': '790',
        'orientation': 'landscape',
    }, {
        'id': '791',
        'orientation': 'portrait',
    }, {
        'id': '795',
        'orientation': 'landscape',
    }, {
        'id': '800',
        'orientation': 'portrait',
    }, {
        'id': '803',
        'orientation': 'portrait',
    }, {
        'id': '806',
        'orientation': 'landscape',
    }, {
        'id': '839',
        'orientation': 'landscape',
    }, {
        'id': '848',
        'orientation': 'landscape',
    }, {
        'id': '860',
        'orientation': 'landscape',
    }, {
        'id': '886',
        'orientation': 'landscape',
    }, {
        'id': '889',
        'orientation': 'portrait',
    }, {
        'id': '890',
        'orientation': 'portrait',
    }, {
        'id': '911',
        'orientation': 'portrait',
    }, {
        'id': '917',
        'orientation': 'portrait',
    }, {
        'id': '923',
        'orientation': 'landscape',
    }, {
        'id': '927',
        'orientation': 'landscape',
    }, {
        'id': '934',
        'orientation': 'portrait',
    }, {
        'id': '939',
        'orientation': 'landscape',
    }, {
        'id': '948',
        'orientation': 'landscape',
    }, {
        'id': '961',
        'orientation': 'landscape',
    }, {
        'id': '966',
        'orientation': 'landscape',
    }, {
        'id': '977',
        'orientation': 'portrait',
    }, {
        'id': '994',
        'orientation': 'landscape',
    }, {
        'id': '995',
        'orientation': 'landscape',
    }, {
        'id': '1003',
        'orientation': 'portrait',
    }, {
        'id': '1012',
        'orientation': 'portrait',
    }, {
        'id': '1018',
        'orientation': 'portrait',
    }, {
        'id': '1054',
        'orientation': 'landscape',
    }, {
        'id': '1062',
        'orientation': 'landscape',
    }, {
        'id': '1074',
        'orientation': 'portrait',
    }, {
        'id': '1078',
        'orientation': 'landscape',
    }, {
        'id': '1088',
        'orientation': 'landscape',
    }, {
        'id': '1089',
        'orientation': 'portrait',
    }, {
        'id': '1091',
        'orientation': 'portrait',
    }, {
        'id': '1097',
        'orientation': 'portrait',
    }, {
        'id': '1103',
        'orientation': 'landscape',
    }, {
        'id': '1111',
        'orientation': 'portrait',
    }, {
        'id': '1118',
        'orientation': 'portrait',
    }, {
        'id': '1126',
        'orientation': 'portrait',
    }, {
        'id': '1143',
        'orientation': 'landscape',
    }, {
        'id': '1146',
        'orientation': 'landscape',
    }, {
        'id': '1150',
        'orientation': 'portrait',
    }, {
        'id': '1154',
        'orientation': 'landscape',
    }, {
        'id': '1165',
        'orientation': 'portrait',
    }, {
        'id': '1167',
        'orientation': 'portrait',
    }, {
        'id': '1170',
        'orientation': 'landscape',
    }, {
        'id': '1172',
        'orientation': 'landscape',
    }, {
        'id': '1173',
        'orientation': 'portrait',
    }, {
        'id': '1177',
        'orientation': 'portrait',
    }, {
        'id': '1185',
        'orientation': 'portrait',
    }, {
        'id': '1189',
        'orientation': 'portrait',
    }, {
        'id': '1192',
        'orientation': 'portrait',
    }, {
        'id': '1204',
        'orientation': 'landscape',
    }, {
        'id': '1207',
        'orientation': 'portrait',
    }, {
        'id': '1209',
        'orientation': 'landscape',
    }, {
        'id': '1211',
        'orientation': 'landscape',
    }, {
        'id': '1212',
        'orientation': 'portrait',
    }, {
        'id': '1215',
        'orientation': 'portrait',
    }, {
        'id': '1217',
        'orientation': 'portrait',
    }, {
        'id': '1219',
        'orientation': 'portrait',
    }, {
        'id': '1221',
        'orientation': 'landscape',
    }, {
        'id': '1226',
        'orientation': 'portrait',
    }, {
        'id': '1228',
        'orientation': 'landscape',
    }, {
        'id': '1230',
        'orientation': 'portrait',
    }, {
        'id': '1235',
        'orientation': 'portrait',
    }, {
        'id': '1240',
        'orientation': 'portrait',
    }, {
        'id': '1241',
        'orientation': 'landscape',
    }, {
        'id': '1243',
        'orientation': 'portrait',
    }, {
        'id': '1248',
        'orientation': 'portrait',
    }, {
        'id': '1259',
        'orientation': 'portrait',
    }, {
        'id': '1285',
        'orientation': 'landscape',
    }, {
        'id': '1319',
        'orientation': 'portrait',
    }, {
        'id': '1364',
        'orientation': 'landscape',
    }, {
        'id': '1369',
        'orientation': 'landscape',
    }, {
        'id': '1383',
        'orientation': 'landscape',
    }, {
        'id': '1391',
        'orientation': 'portrait',
    }, {
        'id': '1393',
        'orientation': 'portrait',
    }, {
        'id': '1401',
        'orientation': 'landscape',
    }, {
        'id': '1403',
        'orientation': 'portrait',
    },]

    return render_template('index.html', images=images, debug=DEBUG)


# init
# -----------------------------------------------------------------------------

if __name__ == '__main__':
    app.run(debug=DEBUG, host='0.0.0.0')
